import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import {
  analysisToPortable,
  buildPrintHtml,
  portableFilename,
  portableToJson,
  portableToMarkdown,
  snapshotToPortable,
} from '../public/portable-output.js';

function fixture() {
  return {
    profile: { login: 'alice', name: 'Alice', avatarUrl: 'https://example.com/alice.png' },
    window: { days: 30 },
    report: {
      headline: 'Shipped a portable release workflow',
      summary: 'Packaging and release reliability were the visible story.',
      mainFocus: { repo: 'dev30', title: 'Release readiness', explanation: 'The work centered on shipping.', significance: 'This reduced release friction.' },
      projects: [{ repo: 'dev30', title: 'Portable outputs', description: 'Made the briefing portable.', highlights: ['Markdown export', 'PDF-ready print'] }],
      observations: [{ text: 'Work clustered around release preparation.' }],
      technical: { trajectory: 'Release-focused' },
    },
    workMix: { build: 60, release: 40 },
    repos: [{ name: 'dev30', visibility: 'public', commits: 12, pullRequests: 3, language: 'JavaScript' }],
    evidence: [{ id: 'E1', repo: 'dev30', title: 'Add exports', type: 'pull_request', date: '2026-08-18', url: 'https://github.com/alice/dev30/pull/1' }],
    history: { snapshotId: 'abc-123', generatedAt: '2026-08-18T03:00:00.000Z' },
    meta: { collector: { includePrivate: false }, analysisMode: 'deepseek', model: 'test-model' },
  };
}

test('analysis payload becomes a portable snapshot without UI scraping', () => {
  const portable = analysisToPortable(fixture(), 'en');
  assert.equal(portable.username, 'alice');
  assert.equal(portable.snapshotId, 'abc-123');
  assert.equal(portable.headline, 'Shipped a portable release workflow');
  assert.equal(portable.projects.length, 1);
  assert.equal(portable.evidence.length, 1);
  assert.equal(portable.includePrivate, false);
});

test('saved snapshot payload maps to the same export schema', () => {
  const source = fixture();
  const portable = snapshotToPortable({
    id: 'snap-1', generatedAt: source.history.generatedAt, username: 'alice', days: 30, locale: 'vi', includePrivate: true,
    profile: source.profile, repos: source.repos, workMix: source.workMix, evidence: source.evidence, report: source.report, analysisMode: 'deepseek',
  });
  assert.equal(portable.source, 'snapshot');
  assert.equal(portable.snapshotId, 'snap-1');
  assert.equal(portable.locale, 'vi');
  assert.equal(portable.includePrivate, true);
});

test('Markdown export carries story, repository table and evidence links', () => {
  const markdown = portableToMarkdown(analysisToPortable(fixture(), 'en'));
  assert.match(markdown, /^# Dev30 Snapshot — @alice/m);
  assert.match(markdown, /## Work story/);
  assert.match(markdown, /\| dev30 \| public \| 12 \| 3 \| JavaScript \|/);
  assert.match(markdown, /\[dev30 · Add exports\]\(https:\/\/github\.com\/alice\/dev30\/pull\/1\)/);
  assert.match(markdown, /Generated by \[Dev30\]/);
});

test('JSON export is structured and deterministic enough for integrations', () => {
  const portable = analysisToPortable(fixture(), 'en');
  const parsed = JSON.parse(portableToJson(portable));
  assert.equal(parsed.exportSchemaVersion, 1);
  assert.equal(parsed.username, 'alice');
  assert.equal(parsed.repos[0].name, 'dev30');
  assert.equal(parsed.evidence[0].id, 'E1');
});

test('print document is A4-ready, branded and escapes report HTML', () => {
  const portable = analysisToPortable(fixture(), 'en');
  portable.headline = '<script>alert(1)</script> Shipping';
  const html = buildPrintHtml(portable);
  assert.match(html, /@page\{size:A4/);
  assert.match(html, /Save as PDF/);
  assert.match(html, /Dev30/);
  assert.doesNotMatch(html, /<script>alert\(1\)<\/script>/);
  assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt; Shipping/);
});

test('portable filenames are stable and safe', () => {
  const name = portableFilename(analysisToPortable(fixture(), 'en'), 'md');
  assert.equal(name, 'dev30-alice-30d-2026-08-18.md');
});

test('portable output UI loads after the visual personality layers', async () => {
  const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
  assert.match(html, /pixel-personality\.css[\s\S]*portable-output\.css/);
  assert.match(html, /pixel-personality\.js[\s\S]*portable-output\.js/);
});

test('pixel card stays local and uses a 1200 by 630 canvas with no external rendering service', async () => {
  const source = await readFile(new URL('../public/portable-output.js', import.meta.url), 'utf8');
  assert.match(source, /canvas\.width = 1200; canvas\.height = 630/);
  assert.match(source, /canvas\.toBlob/);
  assert.doesNotMatch(source, /html2canvas|jspdf|cloudinary|imgix/i);
  assert.match(source, /This export may contain information derived from private repositories/);
});
