import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import {
  analysisToPortable,
  buildPrintHtml,
  portableFilename,
  portableSocialHeadline,
  portableToJson,
  portableToMarkdown,
  selectKeyEvidence,
  snapshotToPortable,
} from '../public/portable-output.js';

function fixture() {
  return {
    profile: { login: 'alice', name: 'Alice', avatarUrl: 'https://example.com/alice.png' },
    window: { days: 30 },
    report: {
      headline: 'Shipped a portable release workflow with a long evidence-backed story for developer work',
      summary: 'Packaging and release reliability were the visible story.',
      mainFocus: { repo: 'dev30', title: 'Release readiness', explanation: 'The work centered on shipping.', significance: 'This reduced release friction.', evidenceIds: ['E1'] },
      projects: [{ repo: 'dev30', title: 'Portable outputs', description: 'Made the briefing portable.', highlights: ['Markdown export (E1)', 'PDF-ready print'], evidenceIds: ['E1'] }],
      observations: [{ text: 'Work clustered around release preparation.', evidenceIds: ['E1'] }],
      technical: { trajectory: 'Release-focused', signals: [{ text: 'Release work was visible.', evidenceIds: ['E1'] }] },
    },
    workMix: { build: 60, release: 40 },
    repos: [{ name: 'dev30', visibility: 'public', commits: 12, pullRequests: 3, language: 'JavaScript' }],
    evidence: [{ id: 'E1', repo: 'dev30', title: 'Add exports', type: 'pull_request', date: '2026-08-18', url: 'https://github.com/alice/dev30/pull/1' }],
    history: { snapshotId: 'abc-123', generatedAt: '2026-08-18T03:00:00.000Z' },
    meta: { collector: { includePrivate: false }, analysisMode: 'deepseek', model: 'test-model' },
  };
}

function manyEvidenceFixture(count = 20) {
  const data = fixture();
  data.evidence = Array.from({ length: count }, (_, index) => ({
    id: `E${index + 1}`,
    repo: index < 15 ? 'dev30' : 'other',
    title: `Evidence item ${index + 1}`,
    type: 'pull_request',
    date: '2026-08-18',
    url: `https://github.com/alice/dev30/pull/${index + 1}`,
  }));
  return data;
}

test('analysis payload becomes a portable snapshot without UI scraping', () => {
  const portable = analysisToPortable(fixture(), 'en');
  assert.equal(portable.username, 'alice');
  assert.equal(portable.snapshotId, 'abc-123');
  assert.match(portable.headline, /portable release workflow/);
  assert.equal(portable.projects.length, 1);
  assert.equal(portable.evidence.length, 1);
  assert.equal(portable.includePrivate, false);
});

test('saved snapshot payload maps to the same export schema', () => {
  const source = fixture();
  const portable = snapshotToPortable({
    id: 'snap-1', generatedAt: source.history.generatedAt, username: 'alice', days: 30, locale: 'vi', includePrivate: true,
    profile: source.profile, repos: source.repos, workMix: source.workMix, evidence: source.evidence, report: source.report, analysisMode: 'deepseek',
  });
  assert.equal(portable.source, 'snapshot');
  assert.equal(portable.snapshotId, 'snap-1');
  assert.equal(portable.locale, 'vi');
  assert.equal(portable.includePrivate, true);
});

test('social card headline prefers the concise main-focus title over the raw report headline', () => {
  const portable = analysisToPortable(fixture(), 'en');
  assert.equal(portableSocialHeadline(portable), 'Release readiness');
  assert.ok(portableSocialHeadline(portable).length < portable.headline.length);
});

test('key evidence prioritizes IDs cited by report claims', () => {
  const portable = analysisToPortable(manyEvidenceFixture(), 'en');
  portable.mainFocus.evidenceIds = ['E20'];
  const selected = selectKeyEvidence(portable, 3);
  assert.equal(selected[0].id, 'E20');
  assert.equal(selected.length, 3);
});

test('Markdown export carries traceable evidence IDs, key evidence and the full appendix', () => {
  const markdown = portableToMarkdown(analysisToPortable(fixture(), 'en'));
  assert.match(markdown, /^# Dev30 Snapshot — @alice/m);
  assert.match(markdown, /## Work story/);
  assert.match(markdown, /\| dev30 \| public \| 12 \| 3 \| JavaScript \|/);
  assert.match(markdown, /## Key evidence/);
  assert.match(markdown, /## Full evidence appendix/);
  assert.match(markdown, /\*\*\[E1\]\*\* \[dev30 · Add exports\]\(https:\/\/github\.com\/alice\/dev30\/pull\/1\)/);
  assert.match(markdown, /Evidence IDs such as `E45` map directly/);
  assert.match(markdown, /Generated by \[Dev30\]/);
});

test('JSON export remains the complete machine-readable snapshot', () => {
  const portable = analysisToPortable(fixture(), 'en');
  const parsed = JSON.parse(portableToJson(portable));
  assert.equal(parsed.exportSchemaVersion, 1);
  assert.equal(parsed.username, 'alice');
  assert.equal(parsed.repos[0].name, 'dev30');
  assert.equal(parsed.evidence[0].id, 'E1');
});

test('print document uses explicit zero-margin A4 pages and curated evidence', () => {
  const portable = analysisToPortable(manyEvidenceFixture(20), 'en');
  portable.headline = '<script>alert(1)</script> Shipping';
  const html = buildPrintHtml(portable);
  assert.match(html, /@page\{size:A4;margin:0\}/);
  assert.match(html, /class="page"/);
  assert.match(html, /Key evidence · 12 of 20/);
  assert.match(html, /20 evidence items captured/);
  assert.match(html, /Full evidence stays available in Markdown and Full JSON data/);
  assert.match(html, /Evidence item 12/);
  assert.doesNotMatch(html, /Evidence item 13/);
  assert.match(html, /Save as PDF/);
  assert.doesNotMatch(html, /<script>alert\(1\)<\/script>/);
  assert.match(html, /&lt;script&gt;alert\(1\)&lt;\/script&gt; Shipping/);
});

test('portable filenames are stable and safe', () => {
  const name = portableFilename(analysisToPortable(fixture(), 'en'), 'md');
  assert.equal(name, 'dev30-alice-30d-2026-08-18.md');
});

test('portable output UI loads after the visual personality layers', async () => {
  const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
  assert.match(html, /pixel-personality\.css[\s\S]*portable-output\.css/);
  assert.match(html, /pixel-personality\.js[\s\S]*portable-output\.js/);
});

test('PDF is opened synchronously from the export click and JSON is labeled as full data', async () => {
  const source = await readFile(new URL('../public/portable-output.js', import.meta.url), 'utf8');
  assert.match(source, /button\('PDF',[\s\S]*\(\) => openPrintDocument\(getPortable\(\)\)\)/);
  assert.doesNotMatch(source, /openPrintDocument\(await getPortable\(\)\)/);
  assert.match(source, /'Full JSON data'/);
  assert.match(source, /Machine-readable snapshot \+ full evidence/);
});

test('pixel card stays local, reserves a fixed footer and uses the concise story', async () => {
  const source = await readFile(new URL('../public/portable-output.js', import.meta.url), 'utf8');
  assert.match(source, /canvas\.width = 1200; canvas\.height = 630/);
  assert.match(source, /portableSocialHeadline\(portable\)/);
  assert.match(source, /const footerTop = 548/);
  assert.match(source, /ctx\.textAlign = 'right'/);
  assert.match(source, /canvas\.toBlob/);
  assert.doesNotMatch(source, /html2canvas|jspdf|cloudinary|imgix/i);
  assert.match(source, /This export may contain information derived from private repositories/);
});
